language: cpp
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_script:  
    - sudo apt-get install libboost-python-dev libflann-dev
    - sudo apt-get install libarmadillo-dev
    - sudo pip install numpy
    - sudo apt-get install libatlas-base-dev gfortran
    - sudo pip install scipy
    - mkdir build
    - cd build
    - cmake ..

script: 
	make CXX=$COMPILER -j3  
