
language: cpp

sudo: required

compiler:  
    - g++

before_install:
  # g++4.9
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi

before_script:  
    - sudo apt-get install libboost-python-dev libflann-dev
    - mkdir build
    - cd build
    - cmake ..

script: make  
