language: cpp
sudo: required
dist: trusty

compiler:  
    - g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libusb-1.0-0-dev

before_script:  
    - sudo apt-get install libboost-python-dev libflann-dev
    - mkdir build
    - cd build
    - cmake ..

script: make  
