
language: cpp
sudo: required
dist: trusty

before_script:
    - sudo apt-get install build-essential libarmadillo-dev libflann-dev
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
