
language: cpp
sudo: required
dist: trusty

before_install:
    - sudo apt-get install build-essential
    - sudo apt-get install libboost-python-dev libflann-dev libarmadillo-dev
    - cd npr
    - mkdir build
    - cd build
    - cmake ..
    - make
install:
    - make install
