
language: cpp
sudo: required
dist: XenialXerus

before_install:

  - sudo apt-get install libboost-python-dev libflann-dev libarmadillo-dev python-numpy


before_script:

  - python --version
  - ls /usr/lib/python2.7/dist-packages/apt

script:
  - python install.py
