language: cpp
sudo: required
dist: trusty

compiler:  
    - g++

before_script:  
    - sudo apt-get install libboost-python-dev libflann-dev
    - sudo apt-get install libarmadillo-dev
    - sudo pip install numpy
    - sudo apt-get install libatlas-base-dev gfortran
    - sudo pip install scipy
    - mkdir build
    - cd build
    - cmake ..

script: make  
